import './index.css'
import rightChevron from './assets/chevron-right.svg'
import leftChevron from './assets/chevron-left.svg'
import { useNavigate } from 'react-router-dom'

function AIInDesign() {
  const navigate = useNavigate()

  return (
    <div className="page-canvas">
      <div className="page-content">
        <h1>AI in Design</h1>
        <p>As technology advances, it opens fresh opportunities. It's human nature to experiment and innovate, especially when we find our limitations suddenly lifted. Our understanding of electricity has provided us with light and heat (among many other things) without us needing to tend to an open flame. This simple thing has opened up so many opportunities for us, even if it has indirectly contributed to many late nights.</p>

        <p>As designers, we are problem-solvers, artists and creatives. In a way, this makes us uniquely qualified to make use of new technology. Finding creative solutions or new ways of self-expression is something we are very in tune with. There are several utilities for AI in design and there will likely be more developed in the near future. We will explore a few of these here.</p>

        <h2>Typical Input-Output</h2>
        
        <p>More often than not, AI functions for design will fall into one of the following categories. Each describes the type of input that is provided by the user and the type of output that is generated by the AI:</p>

        <ul>
          <li>Text-to-Text</li>
          <li>Text-to-Image</li>
          <li>Text-to-Video</li>
          <li>Image-to-Image</li>
          <li>Image-to-Video</li>
        </ul>

        <p>One of the most basic uses for AI is quick, effortless content generation. For many people, this will be their first experience with Generative AI. Chances are, this will either really impress you or really underwhelm you. The speed with which it can generate content is remarkable, but the quality can be hit-or-miss. </p>

        <p>Even with a long, well-written prompt, a Generative Model will often need several attempts before it creates something acceptable by the user. There may also be persistent errors in its content depending on the data it draws from that make what it generates seem strange or amateurish. In the worst case, we have seen relatively benign prompts result in nightmarish images or offensive language. While the quality of AI content will undoubtably improve over time, it's important to carefully review any content generated with AI.</p>

        <h2>Rapid Ideation</h2>

        <p>This was mentioned earlier in this guide, but it's worth reiterating how helpful it can be to visualize your ideas quickly. With an AI tool you can see many variations of an idea in a matter of seconds. These can be further fine-tuned with additional input. In the case of Chatbots you are able to build and refine your ideas in the form of a conversation. Even when you only have a vague idea of what you want (or especially in that case) it can help to simply 'talk' through the idea. In some cases, you may not have an expert or even another person available to bounce ideas off of.</p>

        <p>This isn't just about saving time either. The easier it is to take what's in our heads and translate it into physical form, the less of a risk it becomes to experiment with ideas. It is common when planning a project to sketch a number of possible designs with pencil and paper simply because it's quick and relatively easy. Although this experience isn't exactly the same as prompting an AI, it can help in a similar way.</p>

        <h2>Patterns and Best Practices</h2>

        <p>One of the strengths of AI is in pattern recognition and coincidentally, patterns are something used often in Graphic Design. In this case, we're referring to designs and layouts that were made for a particular purpose and have become standard solutions. This is very common in practices such as User Interface Design and User Experience Design. In this case, AI can be trained to construct a user interface when provided with a description of the user’s needs. The AI can associate certain needs with corresponding design patterns and construct an interface using those patterns.</p>

        <p>Design is a creative profession, but often we find ourselves relying on patterns and methods developed by others. The Golden Ratio in artwork, the Rule of Thirds in cinematography and even simple web components like Checkboxes can be seen as examples of reliable design patterns. That isn't to say that creativity doesn't exist, only that when our daily work is solving common problems it isn't always necessary to find a completely new solution. Automating this process, theoretically, allows us to save our creative energy for where it matters.</p>

        <h2>Data Analysis and User Research</h2>

        <p>One of the most important, if not the most important, parts of the design process is research. Developing a quality product requires knowing the needs and preferences of your users, customers or audience. Translating these needs into actionable solutions is what makes us designers, but gathering this information can entail a lot of work that isn't necessarily design. Large projects will sometimes have entire teams dedicated to user research.</p>

        <p>Again, this is where pattern recognition comes into play. AI can help with user research by analyzing massive amounts of data and finding connections. There are plenty of tools we can use to compare and visualize data points, but not all of these connections will be expected or easily found. Finding trends in a database with thousands of attributes for each data entry may be impossible without the right tools. Granted, this isn't a scenario that every designer would find themselves in, but it's worth mentioning the possibilities.<button className="annotation" onClick={() => navigate('/cited-resources', { state: { id: 'cr-13' } })}>[13]</button><button className="annotation" onClick={() => navigate('/cited-resources', { state: { id: 'cr-14' } })}>[14]</button></p>
        <div className="pageNav">
          <div
            className="wia-nav wia-nav-prev"
            role="button"
            tabIndex={0}
            onClick={() => navigate('/ai-outside-design')}
            onKeyDown={(event) => {
              if (event.key === 'Enter' || event.key === ' ') {
                event.preventDefault()
                navigate('/ai-outside-design')
              }
            }}
          >
            <img src={leftChevron} alt="" aria-hidden="true" />
            <span>AI Outside of Design</span>
          </div>
        
          <div
            className="wia-nav wia-nav-next"
            role="button"
            tabIndex={0}
            onClick={() => navigate('/ai-powered-software')}
            onKeyDown={(event) => {
              if (event.key === 'Enter' || event.key === ' ') {
                event.preventDefault()
                navigate('/ai-powered-software')
              }
            }}
          >
            <span>AI-Powered Software</span>
            <img src={rightChevron} alt="" aria-hidden="true" />
          </div>

        </div>
      </div>
    </div>
  )
}

export default AIInDesign
